# Generated by Django 4.2.5 on 2023-09-10 12:00

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("blogs", "0002_post_dislikes_post_likes_post_mage"),
    ]

    operations = [
        migrations.RenameField(
            model_name="post",
            old_name="mage",
            new_name="image",
        ),
    ]
