# Generated by Django 4.2.5 on 2023-09-15 06:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blogs", "0003_rename_mage_post_image"),
    ]

    operations = [
        migrations.RenameField(
            model_name="post",
            old_name="body",
            new_name="content",
        ),
        migrations.RenameField(
            model_name="post",
            old_name="image",
            new_name="thumbnail",
        ),
        migrations.AddField(
            model_name="post",
            name="overview",
            field=models.TextField(
                default=1,
                help_text="Enter a brief overview or summary of the post here.",
                max_length=1000,
            ),
            preserve_default=False,
        ),
    ]
