# Generated by Django 4.2.5 on 2023-09-15 12:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blogs", "0004_rename_body_post_content_rename_image_post_thumbnail_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="comment",
            name="edited",
            field=models.BooleanField(default=False),
        ),
    ]
