# Generated by Django 4.2.5 on 2023-09-15 14:57

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("blogs", "0006_category"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="category",
            options={
                "ordering": ["title"],
                "verbose_name": "Category",
                "verbose_name_plural": "Categories",
            },
        ),
    ]
