# Generated by Django 4.2.5 on 2023-09-12 08:07

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0002_alter_customuser_managers"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="followers",
            field=models.ManyToManyField(
                blank=True, related_name="following", to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="headline",
            field=models.CharField(
                blank=True,
                help_text="Enter a brief headline that describes you or your role",
                max_length=255,
                null=True,
            ),
        ),
    ]
